project_id = "uxttxsscvirkgvnltvfd"

[functions.parse-efatura-pdf]
verify_jwt = false

[functions.nif-lookup]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.receive-email]
verify_jwt = false

[functions.gmail-auth-callback]
verify_jwt = false

[functions.scan-gmail-invoices]
verify_jwt = false

[functions.nylas-webhook]
verify_jwt = false
