
-- Add missing columns to suppliers table for NIF.pt enrichment
ALTER TABLE public.suppliers
  ADD COLUMN IF NOT EXISTS alias TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS county TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS fax TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS cae TEXT,
  ADD COLUMN IF NOT EXISTS legal_nature TEXT,
  ADD COLUMN IF NOT EXISTS share_capital NUMERIC(14, 2),
  ADD COLUMN IF NOT EXISTS share_capital_currency TEXT DEFAULT 'EUR',
  ADD COLUMN IF NOT EXISTS activity_description TEXT,
  ADD COLUMN IF NOT EXISTS nif_pt_url TEXT,
  ADD COLUMN IF NOT EXISTS last_lookup_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS lookup_success BOOLEAN DEFAULT FALSE;
